load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "EABase",
    hdrs = glob(["include/**/*"]),
    includes = ["include/Common"],
    strip_include_prefix = "include/Common",
)

alias(
    name = "eabase",
    actual = ":EABase",
)
